#!/usr/bin/env python3
"""Parse an OpenClaw SKILL.md into Devin playbook and knowledge files."""

import sys
import os
import re
from datetime import datetime, timezone


def parse_frontmatter(content):
    """Extract YAML frontmatter fields."""
    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}, content

    frontmatter = parts[1].strip()
    body = parts[2].strip()

    fields = {}
    for line in frontmatter.split("\n"):
        match = re.match(r"^(\w+):\s*(.+)$", line)
        if match:
            fields[match.group(1)] = match.group(2).strip()

    return fields, body


def extract_sections(body):
    """Extract markdown sections from the body."""
    sections = {}
    current_section = None
    current_content = []

    for line in body.split("\n"):
        header_match = re.match(r"^##\s+(.+)$", line)
        if header_match:
            if current_section:
                sections[current_section] = "\n".join(current_content).strip()
            current_section = header_match.group(1)
            current_content = []
        else:
            current_content.append(line)

    if current_section:
        sections[current_section] = "\n".join(current_content).strip()

    return sections


def generate_playbook(name, description, body, sections, skill_path):
    """Generate a Devin playbook markdown file."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    playbook = f"""# {name}

## Overview
{description}

## When to Use
{sections.get('Overview', 'See skill description.')}

## Instructions
{sections.get('Procedure', sections.get('Instructions', 'Follow the SKILL.md procedure.'))}

"""

    # Add scripts if they exist
    scripts_dir = os.path.join(skill_path, "scripts")
    if os.path.isdir(scripts_dir):
        scripts = [f for f in os.listdir(scripts_dir) if not f.startswith(".")]
        if scripts:
            playbook += "## Available Scripts\n"
            for script in sorted(scripts):
                playbook += f"- `scripts/{script}`\n"
            playbook += "\n"

    # Add references if they exist
    refs_dir = os.path.join(skill_path, "references")
    if os.path.isdir(refs_dir):
        refs = [f for f in os.listdir(refs_dir) if not f.startswith(".")]
        if refs:
            playbook += "## References\n"
            for ref in sorted(refs):
                playbook += f"- `references/{ref}`\n"
            playbook += "\n"

    # Add specifications and advice
    if "Specifications" in sections:
        playbook += f"## Specifications\n{sections['Specifications']}\n\n"

    if "Advice and Pointers" in sections:
        playbook += f"## Advice\n{sections['Advice and Pointers']}\n\n"

    if "Forbidden Actions" in sections:
        playbook += f"## Forbidden Actions\n{sections['Forbidden Actions']}\n\n"

    playbook += f"---\n*Generated by DevinClaw Skills Parser at {timestamp}*\n*Source: {skill_path}/SKILL.md*\n"

    return playbook


def generate_knowledge(name, description, body, sections, skill_path):
    """Generate a Devin knowledge markdown file."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    knowledge = f"""# Knowledge: {name}

## Overview
{description}

"""

    # Add detailed instructions from all sections
    for section_name, content in sections.items():
        if section_name not in ["Overview"]:  # Skip duplicate
            knowledge += f"## {section_name}\n{content}\n\n"

    # Add resources
    resources = []
    for subdir in ["scripts", "references", "assets"]:
        dir_path = os.path.join(skill_path, subdir)
        if os.path.isdir(dir_path):
            files = [f for f in os.listdir(dir_path) if not f.startswith(".")]
            for f in sorted(files):
                resources.append(f"{subdir}/{f}")

    if resources:
        knowledge += "## Resources\n"
        for r in resources:
            knowledge += f"- `{r}`\n"
        knowledge += "\n"

    knowledge += f"---\n*Generated by DevinClaw Skills Parser at {timestamp}*\n*Source: {skill_path}/SKILL.md*\n"

    return knowledge


def parse_skill(skill_path, output_dir, quiet=False):
    """Parse a skill and generate Devin playbook + knowledge files."""
    skill_file = os.path.join(skill_path, "SKILL.md")

    with open(skill_file, "r", encoding="utf-8") as f:
        content = f.read()

    fields, body = parse_frontmatter(content)
    name = fields.get("name", os.path.basename(os.path.normpath(skill_path)))
    description = fields.get("description", "")
    sections = extract_sections(body)

    # Generate files
    playbook = generate_playbook(name, description, body, sections, skill_path)
    knowledge = generate_knowledge(name, description, body, sections, skill_path)

    # Write output
    os.makedirs(output_dir, exist_ok=True)

    playbook_path = os.path.join(output_dir, f"{name}-playbook.md")
    with open(playbook_path, "w", encoding="utf-8") as f:
        f.write(playbook)

    knowledge_path = os.path.join(output_dir, f"{name}-knowledge.md")
    with open(knowledge_path, "w", encoding="utf-8") as f:
        f.write(knowledge)

    if not quiet:
        print(f"  ✅ {name}")
        print(f"     Playbook:  {playbook_path}")
        print(f"     Knowledge: {knowledge_path}")

    return name, playbook_path, knowledge_path


def main():
    if len(sys.argv) < 2:
        print("Usage: parse_skill.py <skill-directory> [--output-dir <dir>] [--quiet]")
        sys.exit(1)

    skill_path = sys.argv[1]
    output_dir = "."
    quiet = "--quiet" in sys.argv

    if "--output-dir" in sys.argv:
        idx = sys.argv.index("--output-dir")
        if idx + 1 < len(sys.argv):
            output_dir = sys.argv[idx + 1]

    if not os.path.isdir(skill_path):
        print(f"Error: {skill_path} is not a directory")
        sys.exit(1)

    parse_skill(skill_path, output_dir, quiet)


if __name__ == "__main__":
    main()
